# config/config.yaml
orm:
  default:
    mysql: user:password@tcp(localhost:3306)/hitrix_test?charset=utf8mb4&parseTime=True
    redis: localhost:6379:0
    locker: default
    local_cache: 1000

authentication:
  secret: "a-deep-dark-secret"
  support_otp: true
  otp_length: 5

server:
  port: 8080

DATABASE:
  MYSQL:
    DRIVER_NAME: mysql
    USER_NAME: user
    PASSWORD: password
    HOST: localhost
    PORT: 3306
    DATABASE_NAME: hitrix_test

REDIS:
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_ADDR: localhost:6379
  REDIS_STREAM: todos:events

S3:
  S3_ENDPOINT: http://localhost:4566
  S3_BUCKET: todo-bucket

AWS:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1

cors:
  - http://localhost:9001
  - http://localhost:63342